name = "AutoPreallocation"
uuid = "e7028de2-df94-4053-9fdc-99272086b8d4"
authors = ["Lyndon White"]
version = "0.3.1"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BenchmarkTools = "0.5"
Cassette = "0.2, 0.3"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
